### ISSUE TITLE
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appsflyer/internal/connector/purcahse/AFPurchaseConnectorA1u;

### ISSUE THREAD

**Issue by kakawaDEV** [AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector#16]
In my project I have the Appsflyer plugin, an additional Appsflyer Purchase Сonnector and Appsflyer ad-revenue (Everything is updated to the latest version except the main plugin, it is on version v6.14.3). 

I updated the Unity purchase plugin to version 4.12.2 because GooglePlay requires updating the billing library to a new version (which is included in the Unity purchase plugin), but after that the Appsflyer Purchase connector stopped working in the build. It outputs the following:

```
2024/08/07 18:47:14.550 7278 7658 Error Unity AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appsflyer/internal/connector/purcahse/AFPurchaseConnectorA1u;
2024/08/07 18:47:14.550 7278 7658 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appsflyer/internal/connector/purcahse/AFPurchaseConnectorA1u;
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at com.appsflyer.api.PurchaseClient$Builder.build(:243)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at com.appsflyer.unity.afunitypurchaseconnector.AppsFlyerAndroidWrapper.build(AppsFlyerAndroidWrapper.java:47)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at android.os.Looper.loopOnce(Looper.java:233)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at android.os.Looper.loop(Looper.java:344)
2024/08/07 18:47:14.550 7278 7658 Error Unity 	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
2024/08/07 18:47:14.550 7278 7658 Error Unity Caused by: java.lang.ClassNotFoundException: com.appsflyer.internal.connector.purcahse.AFPurchaseConnectorA1u
2024/08/07 18:47:14.550 7278 7658 Error Unity 	... 9 more
2024/08/07 18:47:14.550 7278 7658 Error Unity   at UnityEngine.AndroidJNISafe.CheckException (
```
Purchases work through the use of Unity's Codeless IAP.

Tell me, what could be the reason for the error? Can I fix this quickly?

**Comment by kakawaDEV** [comment]
nvm, it turned out that this is a problem with the Unity shopping plugin itself.

The guide on how to fix this is [here](https://discussions.unity.com/t/getting-unityengine-androidjavaexception-java-lang-classnotfoundexception-after-upgrading-to-unity-iap-4-12-2/1496001)
